version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - nearby-network

  location-service:
    build: ./location-service
    container_name: location-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - nearby-network

networks:
  nearby-network:
    driver: bridge
